import salary
basic = int(input("Enter a basic salary:"))
hra = int(input("Enter a hra:"))
allowance = int(input("Enter a allowance:"))
total = salary.calculate_salary(basic, hra, allowance)
print("employee sarary calculation:")
print("Basic Salary:", basic)
print("HRA:", hra)
print("Allowance:", allowance)
print("Total Salary:", total)
